config/routes.rb
Rails.application.routes.draw do

  resources :scenarios do
    collection do
      get 'get-restaurants'
    end
  end

  root 'starter#home'

  get 'configuration' => 'starter#configuration'
  get 'assessor' => 'assessor#home'
  get 'sample' => 'assessor#sample'

end

app/controllers/assessor_controller.rb
class AssessorController < ApplicationController

  before_action :set_scenario, only: [:home]

  # GET /scenarios
  def home
    nearby_list = eval(@scenario.nearby_restaurants)
    nearby_list.push @scenario.zomato_restaurant_id
    @ranked_list = Scenario.where(zomato_restaurant_id: nearby_list).order(ranking_score: :desc)
    @favorites = []
    @distance = []
    @ranked_list.each do |item|
      # Get the fav menu item for each restaurant
      reviews = Review.select('id').where(restaurant_id: item.zomato_restaurant_id).all.as_json
      arr = []
      reviews.each do |review| arr.push review['id'] end
      reviews = arr
      entity = Entity.where(review_id: reviews).where(sentiment_type: 'positive').order(sentiment: :desc)
      @favorites[item.zomato_restaurant_id] = entity.count != 0 ? entity.first.entity : 'Not available'
      # Get distance of each restaurant from primary restaurant
      response = RestClient.get "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{item.location_lat},#{item.location_lng}&destinations=#{@scenario.location_lat},#{@scenario.location_lng}&key=#{Rails.application.config.google_key}"
      response = JSON.parse(response)
      if response['status'] == 'OK' and response['rows'][0]['elements'][0]['status'] == 'OK'
        @distance[item.zomato_restaurant_id] = (response['rows'][0]['elements'][0]['distance']['value']*0.000621371).to_i.to_s
      else
        @distance[item.zomato_restaurant_id] = 'NA'
      end
    end

    # Get Neighborhood History
    @history = @scenario.comprehensive_rating_history

    #Food Quality
    @food_quality = @scenario.get_food_quality

    #Pop Stats
    @pop_stats = @scenario.get_pop_stats
    @pop_entities = {}
    @pop_entities[:white] = (@pop_stats[:whites]*100)/@pop_stats[:total]
    @pop_entities[:black] = (@pop_stats[:blacks]*100)/@pop_stats[:total]
    @pop_entities[:hispanic] = (@pop_stats[:hispanics]*100)/@pop_stats[:total]
    @pop_entities[:natives] = (@pop_stats[:american_natives]*100)/@pop_stats[:total]
    @pop_entities[:indian] = (@pop_stats[:indians]*100)/@pop_stats[:total]
    @pop_entities[:chinese] = (@pop_stats[:chinese]*100)/@pop_stats[:total]

  end

  # GET /sample.json
  def sample
    # @pop = Scenario.where(primary: true).first.get_pop_stats

    # response = RestClient.post 'https://api.textrazor.com', {'extractors' => 'entities,words,relations,senses', 'text' => "This place isn't good. Very small spread populated by underwhelming dishes. The naan was dry and thin--perhaps it had been hanging out with some local tortillas and picked up some bad habbits. The saag paneer was mediocre and the tandoori chicken was dry as a bone. All the dishes were run of the mill. Now for the interesting part! Somebody elses dishes and glass (complete with a straw that neither I or my companion never use) magically appeared on our table between trips to the buffet. I subsequently lost my appetite upon discovering an extra fork and realizing I may have not used my own! My partner's jacket was still at the table so we know we weren't sitting at the wrong table. Management was nice enough to replace my silverware and drink, but given the subpar food and my experience, I'll never go back."}, {'x-textrazor-key' => '0d6ca499a870c7b9e3b81b4933d8634a4c849fd01b41bfaee29f0b4f'}
    # response = JSON.parse response

    # @history = Scenario.where(primary: true).last.comprehensive_rating_history

    # arr = []
    # @reviews.each do |item| arr.push item['id'] end
    # @reviews = arr
    # @entities = Entity.where.not(property: '').where(review_id: @reviews).all

    # sentiments = '{"Hello":"wish", "there":[{"elsewhere":"google here"}]}'
    # sentiments = JSON.parse sentiments
    # @sent = ''
    # sentiments['there'][0].each {|k,v|
    #   @sent = k if v.include? 'google'
    # }

    # ent = []
    # if response['response']['entities'] && response['response']['sentences'] && response['response']['properties']
    #   response['response']['entities'].each do |entity|
    #     if entity['freebaseTypes'].to_s.include? 'food'
    #       prop_sentence = ''
    #       response['response']['properties'].each do |property|
    #         if (property['wordPositions'] & entity['matchingTokens']) == entity['matchingTokens']
    #           property['propertyPositions'].each do |prop_word_num|
    #             response['response']['sentences'].each do |sentence|
    #               sentence['words'].each do |word|
    #                 if word['position'] == prop_word_num
    #                   prop_sentence << ' ' << word['token']
    #                 end
    #               end
    #             end
    #           end
    #         end
    #       end
    #       ent.push({
    #                    'entity' => entity['matchedText'],
    #                    'property' => prop_sentence,
    #                    'entity_type' => entity['freebaseTypes']
    #                })
    #     end
    #   end
    # end
    # respond_to do |format|
    #   format.json { render :json => response}
    # end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_scenario
      id = params[:id].nil? ? Scenario.where(primary: true).last.id : params[:id]
      @scenario = Scenario.find(id)
    end

end

app/helpers/assessor_helper.rb
module AssessorHelper
end

app/views/assessor/home.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="ibox">
      <h1> <%= @scenario.business_name %></h1><br>

      <div class="mg-left-5">
        <p>
          <strong>Email</strong><br>
          <%= @scenario.email %>
        </p>

        <p>
          <strong>Address</strong><br>
          <%= @scenario.zomato_address %>
        </p>

        <p>
          <strong>Cuisines</strong><br>
          <%= @scenario.zomato_cuisines %>
        </p>

        <p>
          <strong>Online delivery</strong><br>
          <%= @scenario.zomato_has_online_delivery %>
        </p>

        <p>
          <strong>Zomato user rating</strong><br>
          <%= @scenario.zomato_user_rating %>
        </p>

        <p>
          <strong>Zomato rating</strong><br>
          <%= @scenario.zomato_rating_text %>
        </p>

        <p>
          <strong>Zomato rating</strong><br>
          <%= @scenario.zomato_price_range %>
        </p>

        <p id="loc_lat" hidden><%= @scenario.location_lat %></p>
        <p id="loc_lng" hidden><%= @scenario.location_lng %></p>

        <%= link_to 'Back', scenarios_path, class: 'btn btn-primary float-right' %>
        <%= link_to 'Edit', edit_scenario_path(@scenario), class: 'btn btn-success float-right mg-right-10' %>
      </div>
    </div>
        <div class="panel activity-container">
          <div class="glyph text-center activity-icons">
            <div class="glyph-icon flaticon-sky"></div><h4><%= @scenario.get_activity_metrics %><small> Rank</small></h4>
          </div>
          <div class="glyph text-center  activity-icons">
            <div class="glyph-icon flaticon-shape"></div><h4><small><%= @favorites[@scenario.zomato_restaurant_id] %></small></h4>
          </div>
          <div class="glyph text-center  activity-icons">
            <div class="glyph-icon flaticon-shapes"></div><h4><%= @scenario.get_favorability %><small> Odds</small></h4>
          </div>
        </div>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading" id="history-header">
        <a href="#" onclick="event.preventDefault()"><h4>Food Quality in the neighborhood</h4></a>
      </div>

      <div class="panel-container" id="historical-graph">
        <%= pie_chart(@food_quality) %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="pop-stats row mg-bottom-20">
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'British' or
              @scenario.zomato_cuisines.include? 'Italian' or
              @scenario.zomato_cuisines.include? 'French' or
              @scenario.zomato_cuisines.include? 'Fast Food' or
              @scenario.zomato_cuisines.include? 'Breakfast' or
              @scenario.zomato_cuisines.include? 'Burger' or
              @scenario.zomato_cuisines.include? 'Cafe' or
              @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'Coffee and Tea' or
              @scenario.zomato_cuisines.include? 'International'
      %>"><div class="glyph-icon flaticon-black"></div><%= "#{@pop_stats[:whites]}K whites" %></div>
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'French' or
              @scenario.zomato_cuisines.include? 'Fast Food' or
              @scenario.zomato_cuisines.include? 'Breakfast' or
              @scenario.zomato_cuisines.include? 'Burger' or
              @scenario.zomato_cuisines.include? 'Cafe' or
              @scenario.zomato_cuisines.include? 'Chili'
      %>"><div class="glyph-icon flaticon-people-1"></div><%= "#{@pop_stats[:blacks]}K blacks" %></div>
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'Fast Food' or
              @scenario.zomato_cuisines.include? 'Breakfast' or
              @scenario.zomato_cuisines.include? 'Burger' or
              @scenario.zomato_cuisines.include? 'Cafe' or
              @scenario.zomato_cuisines.include? 'Chili' or
              @scenario.zomato_cuisines.include? 'Mexican' or
              @scenario.zomato_cuisines.include? 'Mediterranean'
      %>"><div class="glyph-icon flaticon-human"></div><%= "#{@pop_stats[:hispanics]}K hispanics" %></div>
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'American' or
              @scenario.zomato_cuisines.include? 'Mexican' or
              @scenario.zomato_cuisines.include? 'Chili' or
              @scenario.zomato_cuisines.include? 'Cafe' or
              @scenario.zomato_cuisines.include? 'Mediterranean'
      %>"><div class="glyph-icon flaticon-people-2"></div><%= "#{@pop_stats[:american_natives]}K natives" %></div>
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'Asian' or
              @scenario.zomato_cuisines.include? 'Chinese' or
              @scenario.zomato_cuisines.include? 'Japanese' or
              @scenario.zomato_cuisines.include? 'Korean' or
              @scenario.zomato_cuisines.include? 'Indonesian' or
              @scenario.zomato_cuisines.include? 'Vietnamese'
      %>"><div class="glyph-icon flaticon-people"></div><%= "#{@pop_stats[:chinese]}K chinese" %></div>
      <div class="glyph text-center <%= 'favorite-pop' if @scenario.zomato_cuisines.include? 'Asian' or
              @scenario.zomato_cuisines.include? 'Chinese' or
              @scenario.zomato_cuisines.include? 'Indian' or
              @scenario.zomato_cuisines.include? 'Nepalese' or
              @scenario.zomato_cuisines.include? 'Cafe' or
              @scenario.zomato_cuisines.include? 'Chili' or
              @scenario.zomato_cuisines.include? 'Mexican'
      %>"><div class="glyph-icon flaticon-people-3"></div><%= "#{@pop_stats[:indians]}K indians" %></div>
    </div>
    <div class="row">
      <div class="col-lg-5 pop-stats-icons">
        <div class="glyph text-center"><div class="glyph-icon flaticon-man"></div><%= "#{@pop_stats[:males]}K males" %></div>
        <div class="glyph text-center"><div class="glyph-icon flaticon-signs"></div><%= "#{@pop_stats[:females]}K females" %></div>
        <div class="glyph text-center"><div class="glyph-icon flaticon-social"></div><%= "#{@pop_stats[:total]}K" %></div>
      </div>
      <div class="col-lg-7 pop-stats-icons">
        <%= pie_chart @pop_entities %>
    </div>
  </div>
    <!--<div class="google-map-small-container mg-bottom-20 mg-top-20">-->
      <!--<div id="google-map"></div>-->
    <!--</div>-->

    <div class="panel panel-default mg-top-20">
      <!-- Default panel contents -->
      <div class="panel-heading" id="ranking-header">
        <button type="button" id="toggle-detail-ranking" class="btn btn-primary float-right">Toggle Details</button>
        <a href="#" onclick="event.preventDefault()"><h4>This is where you stand in the competition...</h4></a>
      </div>

      <div class="panel-container" id="ranking-table" hidden>
        <!-- Table -->
        <div id="normal-table">
          <table class="table">
            <thead>
            <tr>
              <th>Rank</th>
              <th>Business name</th>
              <th>Menu's favorite</th>
              <th>Rating</th>
              <th>Votes</th>
              <th>Distance</th>
            </tr>
            </thead>

            <tbody>
            <% iterator = 0 %>
            <% @ranked_list.each do |item| %>
                <% iterator += 1 %>
                <tr>
                  <td><%= iterator %></td>
                  <td><%= item.business_name %></td>
                  <td><%= @favorites[item.zomato_restaurant_id] %></td>
                  <td><%= item.zomato_user_rating %></td>
                  <td><%= item.zomato_votes_count %></td>
                  <td><%= @distance[item.zomato_restaurant_id] + ' mi' %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <!-- Table end -->
        <!-- Panel Body -->
        <div id="detailed-table" hidden>
          <% iterator = 0 %>
          <% @ranked_list.each do |nearby_rest| %>
              <% iterator += 1 %>
              <%= link_to nearby_rest, class: 'list-group-item' do %>
                  <h4 class="list-group-item-heading"><%= '#' << iterator.to_s << ' ' << nearby_rest.business_name %> <small>at <%= nearby_rest.zomato_address %></small></h4>
                  <table>
                    <tr>
                      <td><strong>Cuisines</strong><br><%= nearby_rest.zomato_cuisines %></td>
                      <td><strong>User rating</strong><br><%= nearby_rest.zomato_user_rating %></td>
                      <td><strong>Users rated as</strong><br><%= nearby_rest.zomato_rating_text %></td>
                      <td><strong>No. of users voted</strong><br><%= nearby_rest.zomato_votes_count%></td>
                    </tr>
                    <tr>
                      <td><strong>Price range</strong><br><%= nearby_rest.zomato_price_range %></td>
                      <td><strong>Cost for two</strong><br><%= nearby_rest.zomato_average_cost_for_two %></td>
                      <td><strong>Online delivery</strong><br><%= nearby_rest.zomato_has_online_delivery %></td>
                      <td><strong>Distance from you</strong><br><%= @distance[nearby_rest.zomato_restaurant_id] + 'mi' %></td>
                    </tr>
                  </table>
              <% end %>
          <% end %>
        </div>
        <!-- -->
      </div>
    </div>
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading" id="history-header">
        <a href="#" onclick="event.preventDefault()"><h4>Historical performance</h4></a>
      </div>

      <div class="panel-container" id="historical-graph">
        <%= line_chart [{name: 'Neighborhood', data: @history[0]}, {name: 'Your Business', data: @history[1]}]  %>
      </div>
    </div>
    <!-- -->
  </div>
</div>